---
title: "The Paper"
output: html_notebook
---

```{r}
## read the data in
fa_data <- read.csv("MR_.25_14_FINALfa_new.csv")

## change id factor variables
fa_data <- within(fa_data, {
    ID <- factor(ID)
    Sex <- factor(Sex, levels = 0:1, labels = c("Male", "Female"))
    PrExp <- factor(PrExp)
    NormA <- NormalizedTotalKetamineIsoflurane
})

colnames(fa_data)[15:49] <- substring(colnames(fa_data)[15:49],5)

fa_data
```

```{r}
## LOWESS FIT FOR 0 EXP MODEL

fa_0exp <- fa_data[fa_data$PrExp==0,]
fa_lt600 <- fa_data[fa_data$Age<=600,]

# covtest[j,14] <- summary(mod1)[1] + summary(mod1)[2]*1095+I((1095-mod2_knot1[i])*ifelse(1095<mod2_knot1[i],0,1))*summary(mod1)[3]+I((1095-mod2_knot2[i])*ifelse(1095<mod2_knot2[i],0,1))*summary(mod1)[4]pdf("lowess0.pdf", width=8, height=4)

pdf("lowess0.pdf", width=8, height=4)

par(mfrow = c(1, 2))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in c(1,20)) {
  x <- fa_0exp$Age
  y <- fa_0exp[, i+14]

  lfit <- lowess(x, y, f=.9)
  
  plot(lfit, type='l',lwd = 3, axes=FALSE, xlim=c(0,600), ylim=c(.26,.56),main = names(fa_data[i+14]),col=3)
  points(x, y, pch=20,col = "black")
  axis(1, col = "grey40", col.axis = "grey20", at = seq(0,600, 100))
  if (i ==1) axis(2, col = "grey40", col.axis = "grey20", at = seq(0.2,0.6,.05))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 


pdf("lowess1.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 1:18) {
  x <- fa_0exp$Age
  y <- fa_0exp[, i+14]

  lfit <- lowess(x, y, f=.9)
  
  plot(lfit, type='l',lwd = 3, axes=FALSE, xlim=c(0,600), ylim=c(.2,.55),main = names(fa_data[i+14]),col=3)
  points(x, y, pch=20,col = "black")
  if (i %in% 16:18) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,600, 100))
  if (i %in% seq(1, 18, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(0.2,0.6,.05))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 

pdf("lowess2.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 19:35) {
  x <- fa_0exp$Age
  y <- fa_0exp[, i+14]

  lfit <- lowess(x, y, f=.9)
  
  plot(lfit, type='l',lwd = 3, axes=FALSE, xlim=c(0,600), ylim=c(.2,.55),main = names(fa_data[i+14]),col=3)
  points(x, y, pch=20,col = "black")
  if (i %in% 34:35) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,600, 100))
  if (i %in% seq(19, 35, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(0.2,0.6,.05))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 
```

```{r}
## LOWESS FIT RESIDUAL PLOTS FOR NA

fa_0exp <- fa_data[fa_data$PrExp==0,]
fa_lt600 <- fa_data[fa_data$Age<=600,]

# 2 PLOTS IN MAIN PAPER

pdf("Residuals0.pdf", width=8, height=4)

par(mfrow = c(1, 2))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in c(1,20)) {
  x <- fa_0exp$Age
  y <- fa_0exp[, i+14]

  lfit <- lowess(x, y,f=.9)

  x600 <- fa_lt600$Age
  y600 <- fa_lt600[, i+14]
  
  falowessfun <- approxfun(lfit)
  fitted <- falowessfun(x600)                         
  resid <- (y600-fitted)/y600
  
  plot(fa_lt600$NormA,resid,axes=FALSE, xlim=c(0,12), ylim=c(-.15,.12),main = names(fa_data[i+14]))
  lines(lowess(fa_lt600$NormA[fa_lt600$PrExp!=0], resid[fa_lt600$PrExp!=0]))
  axis(1, col = "grey40", col.axis = "grey20", at = seq(0,12, 2))
  if (i ==1) axis(2, col = "grey40", col.axis = "grey20", at = seq(-.2,.1,.05))
  box(col = "grey60")
  mtext("Normalized Anesthesia", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off()

# PLOTS IN SUPPLEMENT

pdf("Residuals1.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 1:18) {
  x <- fa_0exp$Age
  y <- fa_0exp[, i+14]

  lfit <- lowess(x, y,f=.9)

  x600 <- fa_lt600$Age
  y600 <- fa_lt600[, i+14]
  
  falowessfun <- approxfun(lfit)
  fitted <- falowessfun(x600)                         
  resid <- (y600-fitted)/y600
  
  plot(fa_lt600$NormA,resid,axes=FALSE, xlim=c(0,12), ylim=c(-.2,.1),main = names(fa_data[i+14]))
  lines(lowess(fa_lt600$NormA[fa_lt600$PrExp!=0], resid[fa_lt600$PrExp!=0]))
  if (i %in% 16:18) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,12, 2))
  if (i %in% seq(1, 18, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(-.2,.1,.05))
  box(col = "grey60")
  mtext("Normalized Anesthesia", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 

pdf("Residuals2.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 19:35) {
  x <- fa_0exp$Age
  y <- fa_0exp[, i+14]

  lfit <- lowess(x, y,f=.9)

  x600 <- fa_lt600$Age
  y600 <- fa_lt600[, i+14]
  
  falowessfun <- approxfun(lfit)
  fitted <- falowessfun(x600)                         
  resid <- (y600-fitted)/y600
  
  plot(fa_lt600$NormA,resid,axes=FALSE, xlim=c(0,12), ylim=c(-.2,.1),main = names(fa_data[i+14]))
  lines(lowess(fa_lt600$NormA[fa_lt600$PrExp!=0][which( !is.na(resid[fa_lt600$PrExp!=0]), arr.ind=TRUE)], na.omit(resid[fa_lt600$PrExp!=0])))
  if (i %in% 34:35) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,12, 2))
  if (i %in% seq(19, 35, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(-.2,.1,.05))
  box(col = "grey60")
  mtext("Normalized Anesthesia", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 

```

```{r}
# OPTIMIZE THE KNOTS

knotrange <- seq(50,400,10)
mod2_r2 <- numeric(35)
mod2_knot1 <- numeric(35)
mod2_knot2 <- numeric(35)

for (j in 1:35)
{
  r2 <- 0
  for (i in knotrange) {
    for (k in seq(i+50,500,10)) {
      mod1 <-miceadds::lm.cluster(data = fa_data, formula = fa_data[,14+j] ~ Age +I((Age-i)*ifelse(Age<i,0,1))+I((Age-k)*ifelse(Age<k,0,1))+NormA, cluster = "ID")
      r2_test <- summary(mod1$lm_res)$r.squared
 
      if(r2_test > r2) 
      {
        r2 <- r2_test
        mod2_r2[j] <- r2
        mod2_knot1[j] <- i
        mod2_knot2[j] <- k
        }
}
  }
}
```

```{r}
## PLOT AGE PREDICTION

agevalues <- seq(0, 1100, 10)
id_lvls <- as.numeric(levels(fa_data$ID))

# 2 PLOTS IN MAIN PAPER

pdf("Age0.pdf", width=8, height=4)

par(mfrow = c(1, 2))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in c(1,20)) {
  sink(tempfile())
  mod1 <-miceadds::lm.cluster(data = fa_data , formula = fa_data[,i+14] ~ Age +I((Age-mod2_knot1[i])*ifelse(Age<mod2_knot1[i],0,1)) +I((Age-mod2_knot2[i])*ifelse(Age<mod2_knot2[i],0,1))+NormA, cluster = "ID")
   predictedfa0 <- summary(mod1)[1,1] + summary(mod1)[2,1]*agevalues+summary(mod1)[3,1]*(agevalues-mod2_knot1[i])*ifelse(agevalues<mod2_knot1[i],0,1)+ summary(mod1)[4,1]*(agevalues-mod2_knot2[i])*ifelse(agevalues<mod2_knot2[i],0,1)
   
   NAbeta <- summary(mod1)[5,1]
   
  sink()
  
  plot(fa_data$Age, fa_data[, i+14 ] - fa_data$NormA*NAbeta, pch=20, cex.lab = 1.3, col = "black",xlim=c(0,1100), ylim = c(.25,.6),main = names(fa_data[i+14]),axes = FALSE)
  
    for(j in id_lvls) {
      lines(fa_data$Age[fa_data$ID==j], fa_data[, i+14 ][fa_data$ID==j] - fa_data$NormA[fa_data$ID==j]*NAbeta, col=200, type="b")
    }
  points(fa_data$Age, fa_data[, i+14 ] - fa_data$NormA*NAbeta, pch=20, axes = FALSE, cex.lab = 1.3, col = "black")
  points(fa_data$Age[which(fa_data$PrExp == 0)], fa_data[, i+14 ][which(fa_data$PrExp == 0)], pch=20, axes = FALSE, cex.lab = 1.3, col = "green")
  lines(agevalues, predictedfa0, col = "red", lwd = 3)

  axis(1, col = "grey40", col.axis = "grey20", at = seq(0,1000, 200))
  if (i ==1) axis(2, col = "grey40", col.axis = "grey20", at = seq(.25,.6,.05))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  
}

dev.off()

# PLOTS IN SUPPLEMENT

pdf("Age1.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 1:18) {
  sink(tempfile())
  mod1 <-miceadds::lm.cluster(data = fa_data , formula = fa_data[,i+14] ~ Age +I((Age-mod2_knot1[i])*ifelse(Age<mod2_knot1[i],0,1)) +I((Age-mod2_knot2[i])*ifelse(Age<mod2_knot2[i],0,1))+NormA, cluster = "ID")
   predictedfa0 <- summary(mod1)[1,1] + summary(mod1)[2,1]*agevalues+summary(mod1)[3,1]*(agevalues-mod2_knot1[i])*ifelse(agevalues<mod2_knot1[i],0,1)+ summary(mod1)[4,1]*(agevalues-mod2_knot2[i])*ifelse(agevalues<mod2_knot2[i],0,1)
   
   NAbeta <- summary(mod1)[5,1]
   
  sink()
  
  plot(fa_data$Age, fa_data[, i+14 ] - fa_data$NormA*NAbeta, pch=20, axes = FALSE, main = names(fa_data[i+14]), cex.lab = 1.3, col = "black",xlim=c(0,1100), ylim = c(.2,.6))
  
    for(j in id_lvls) {
      lines(fa_data$Age[fa_data$ID==j], fa_data[, i+14 ][fa_data$ID==j] - fa_data$NormA[fa_data$ID==j]*NAbeta, col=200, type="b")
    }
  points(fa_data$Age, fa_data[, i+14 ] - fa_data$NormA*NAbeta, pch=20, xlab = "Age (Days)", ylab = names(fa_data[i+14]), cex.lab = 1.3, col = "black")
  points(fa_data$Age[which(fa_data$PrExp == 0)], fa_data[, i+14 ][which(fa_data$PrExp == 0)], pch=20, xlab = "Age (Days)", ylab = names(fa_data[i+14]), cex.lab = 1.3, col = "green")
  lines(agevalues, predictedfa0, col = "red", lwd = 3)
  if (i %in% 16:18) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,1000, 200))
  if (i %in% seq(1, 18, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(.20,.6,.1))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 

pdf("Age2.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 19:35) {
  sink(tempfile())
  mod1 <-miceadds::lm.cluster(data = fa_data , formula = fa_data[,i+14] ~ Age +I((Age-mod2_knot1[i])*ifelse(Age<mod2_knot1[i],0,1)) +I((Age-mod2_knot2[i])*ifelse(Age<mod2_knot2[i],0,1))+NormA, cluster = "ID")
   predictedfa0 <- summary(mod1)[1,1] + summary(mod1)[2,1]*agevalues+summary(mod1)[3,1]*(agevalues-mod2_knot1[i])*ifelse(agevalues<mod2_knot1[i],0,1)+ summary(mod1)[4,1]*(agevalues-mod2_knot2[i])*ifelse(agevalues<mod2_knot2[i],0,1)
   
   NAbeta <- summary(mod1)[5,1]
   
  sink()
  
  plot(fa_data$Age, fa_data[, i+14 ] - fa_data$NormA*NAbeta, pch=20, axes=FALSE, main = names(fa_data[i+14]), cex.lab = 1.3, col = "black",xlim=c(0,1100), ylim = c(.2,.6))
    for(j in id_lvls) {
      lines(fa_data$Age[fa_data$ID==j], fa_data[, i+14 ][fa_data$ID==j] - fa_data$NormA[fa_data$ID==j]*NAbeta, col=200, type="b")
    }
  points(fa_data$Age, fa_data[, i+14 ] - fa_data$NormA*NAbeta, pch=20, xlab = "Age (Days)", ylab = names(fa_data[i+14]), cex.lab = 1.3, col = "black")
  points(fa_data$Age[which(fa_data$PrExp == 0)], fa_data[, i+14 ][which(fa_data$PrExp == 0)], pch=20, xlab = "Age (Days)", ylab = names(fa_data[i+14]), cex.lab = 1.3, col = "green")
  lines(agevalues, predictedfa0, col = "red", lwd = 3)
  if (i %in% 34:35) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,1000, 200))
  if (i %in% seq(19, 35, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(.20,.6,.1))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 

```


```{r}
## PLOT NA PREDICTION

navalues <- seq(0, 12, 1)
id_lvls <- as.numeric(levels(fa_data$ID))

# 2 PLOTS IN MAIN PAPER

pdf("NA0.pdf", width=8, height=4)

par(mfrow = c(1, 2))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in c(1,20)) {
  sink(tempfile())
  mod1 <-miceadds::lm.cluster(data = fa_data , formula = fa_data[,i+14] ~ Age +I((Age-mod2_knot1[i])*ifelse(Age<mod2_knot1[i],0,1)) +I((Age-mod2_knot2[i])*ifelse(Age<mod2_knot2[i],0,1))+NormA, cluster = "ID")
   predictedfa0 <- summary(mod1)[1,1] + summary(mod1)[5,1]*navalues
   
   age1beta <- summary(mod1)[2,1]
   age2beta <- summary(mod1)[3,1]
   age3beta <- summary(mod1)[4,1]
   
  sink()
  
  plot(fa_data$NormA, fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta, pch=20, col = "black",xlim=c(0,12), ylim = c(.22,.38),axes=FALSE, cex.lab=.2,main = names(fa_data[i+14]))
  
  for(j in id_lvls) {
      lines(fa_data$NormA[fa_data$ID==j], (fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta)[fa_data$ID==j], col=200, type="b")
    }
  
  points(fa_data$NormA, fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta, pch=20, col = "black")
  
lines(navalues, predictedfa0, col = "red", lwd = 4)

  axis(1, col = "grey40", col.axis = "grey20", at = seq(0,12, 2))
  if (i ==1) axis(2, col = "grey40", col.axis = "grey20", at = seq(.25,.4,.05))
  box(col = "grey60")
  mtext("Normalized Anesthesia", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off()

# PLOTS IN SUPPLEMENT

pdf("NA1.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 1:18) {
  sink(tempfile())
  mod1 <-miceadds::lm.cluster(data = fa_data , formula = fa_data[,i+14] ~ Age +I((Age-mod2_knot1[i])*ifelse(Age<mod2_knot1[i],0,1)) +I((Age-mod2_knot2[i])*ifelse(Age<mod2_knot2[i],0,1))+NormA, cluster = "ID")
   predictedfa0 <- summary(mod1)[1,1] + summary(mod1)[5,1]*navalues
   
   age1beta <- summary(mod1)[2,1]
   age2beta <- summary(mod1)[3,1]
   age3beta <- summary(mod1)[4,1]
   
  sink()
  
  plot(fa_data$NormA, fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta, pch=20, col = "black",xlim=c(0,12), ylim = c(.15,.42),axes=FALSE, cex.lab=.2,main = names(fa_data[i+14]))
  
  for(j in id_lvls) {
      lines(fa_data$NormA[fa_data$ID==j], (fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta)[fa_data$ID==j], col=200, type="b")
    }
  
  points(fa_data$NormA, fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta, pch=20, col = "black")
  
lines(navalues, predictedfa0, col = "red", lwd = 4)

  if (i %in% 16:18) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,12, 2))
  if (i %in% seq(1, 18, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(.20,.6,.1))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 

pdf("NA2.pdf", width=8, height=11)

par(mfrow = c(6, 3))
par(cex = 0.6,cex.main=1.2)
par(mar = c(0, 0, 2, 0), oma = c(4, 4, 6, 6))
par(tcl = -0.25)
par(mgp = c(2, 0.6, 0))

for(i in 19:35) {
  sink(tempfile())
  mod1 <-miceadds::lm.cluster(data = fa_data , formula = fa_data[,i+14] ~ Age +I((Age-mod2_knot1[i])*ifelse(Age<mod2_knot1[i],0,1)) +I((Age-mod2_knot2[i])*ifelse(Age<mod2_knot2[i],0,1))+NormA, cluster = "ID")
   predictedfa0 <- summary(mod1)[1,1] + summary(mod1)[5,1]*navalues
   
   age1beta <- summary(mod1)[2,1]
   age2beta <- summary(mod1)[3,1]
   age3beta <- summary(mod1)[4,1]
   
  sink()
  
  plot(fa_data$NormA, fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta, pch=20, col = "black",xlim=c(0,12), ylim = c(.15,.42),axes=FALSE, cex.lab=.2,main = names(fa_data[i+14]))
  
  for(j in id_lvls) {
      lines(fa_data$NormA[fa_data$ID==j], (fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta)[fa_data$ID==j], col=200, type="b")
    }
  
  points(fa_data$NormA, fa_data[, i+14 ] - fa_data$Age*age1beta - (fa_data$Age-mod2_knot1[i])*ifelse(fa_data$Age<mod2_knot1[i],0,1)*age2beta -(fa_data$Age-mod2_knot2[i])*ifelse(fa_data$Age<mod2_knot2[i],0,1)*age3beta, pch=20, col = "black")
  
lines(navalues, predictedfa0, col = "red", lwd = 4)

  if (i %in% 34:35) axis(1, col = "grey40", col.axis = "grey20", at = seq(0,12, 2))
  if (i %in% seq(19, 35, by = 3)) axis(2, col = "grey40", col.axis = "grey20", at = seq(.20,.6,.1))
  box(col = "grey60")
  mtext("Age (Days)", side = 1, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
  mtext("Fractional Anisotropy (Residual)", side = 2, outer = TRUE, cex = 0.7, line = 2.2, col = "grey20")
}

dev.off() 

```

```{r}
## ESTIMATES AND P-VALUES

trax <- c(1:35)
covtest <- matrix(nrow=length(trax),ncol=14)

for (j in 1:length(trax)) {
  sink(tempfile())
  
  i <- trax[j]
  
  mod1 <-miceadds::lm.cluster(data = fa_data , formula = fa_data[,i+14] ~ Age +I((Age-mod2_knot1[i])*ifelse(Age<mod2_knot1[i],0,1)) +I((Age-mod2_knot2[i])*ifelse(Age<mod2_knot2[i],0,1))+NormA, cluster = "ID")

  covtest[j,c(1,3,5,7,9)] <- t(summary(mod1)[1:5,1])
  covtest[j,c(2,4,6,8,10)] <- t(summary(mod1)[1:5,4])
  
  covtest[j,11] <- summary(mod1)[1] + summary(mod1)[2]*14 +I((14-mod2_knot1[i])*ifelse(14<mod2_knot1[i],0,1))*summary(mod1)[3] +I((14-mod2_knot2[i])*ifelse(14<mod2_knot2[i],0,1))*summary(mod1)[4]
  
  covtest[j,12] <- summary(mod1)[1] + summary(mod1)[2]*127 +I((127-mod2_knot1[i])*ifelse(127<mod2_knot1[i],0,1))*summary(mod1)[3] +I((127-mod2_knot2[i])*ifelse(127<mod2_knot2[i],0,1))*summary(mod1)[4]  
  
  covtest[j,13] <- summary(mod1)[1] + summary(mod1)[2]*275 +I((275-mod2_knot1[i])*ifelse(275<mod2_knot1[i],0,1))*summary(mod1)[3] +I((275-mod2_knot2[i])*ifelse(275<mod2_knot2[i],0,1))*summary(mod1)[4]  
  
  covtest[j,14] <- summary(mod1)[1] + summary(mod1)[2]*1095 +I((1095-mod2_knot1[i])*ifelse(1095<mod2_knot1[i],0,1))*summary(mod1)[3] +I((1095-mod2_knot2[i])*ifelse(1095<mod2_knot2[i],0,1))*summary(mod1)[4]
  
  sink()
}

covtest <- data.frame(covtest)
rownames(covtest) <- names(fa_data[14+trax])
colnames(covtest) <- c('Intercept','p','Age','p','Age2','p','Age3','p','NA','p','14d','127d','275d','1095d')
covtest["knot1"] <- mod2_knot1
covtest["knot2"] <- mod2_knot2


covtest
```

